# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{diff}
  s.version = "0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Marreck", "Lars Christensen", "pmarreck"]
  s.date = %q{2012-04-19}
  s.description = %q{Pure Ruby implementation of unix 'diff'}
  s.email = %q{lumbergh@gmail.com}
  s.extra_rdoc_files = ['LICENSE', 'README']
  s.files = Dir.glob('{bin,lib,test}/**/*') + ['LICENSE', 'README', 'VERSION']
  s.homepage = %q{https://github.com/pmarreck/diff}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Pure Ruby implementation of unix 'diff'}
  s.test_files = Dir.glob('test/**/*')

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('0.4.0') then
    else
    end
  else
  end
end